/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary": "#735c00",
        "tertiary-fixed": "#ffdad4",
        "primary-fixed": "#d4e3ff",
        "surface-variant": "#e4e2dd",
        "primary": "#2765F7",
        "on-background": "#1b1c19",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "tertiary-container": "#470000",
        "secondary-container": "#fed65b",
        "on-surface-variant": "#43474e",
        "secondary-fixed": "#ffe088",
        "inverse-surface": "#30312e",
        "primary-container": "#001f3f",
        "error": "#ba1a1a",
        "tertiary": "#160000",
        "surface-container-highest": "#e4e2dd",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "outline": "#74777f",
        "surface-bright": "#fbf9f4",
        "on-primary-container": "#6f88ad",
        "surface-tint": "#476083",
        "on-tertiary-fixed": "#410000",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-container": "#745c00",
        "surface": "#fbf9f4",
        "inverse-on-surface": "#f2f1ec",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#afc8f0",
        "on-primary-fixed-variant": "#2f486a",
        "tertiary-fixed-dim": "#ffb4a8",
        "on-secondary-fixed-variant": "#574500",
        "on-surface": "#1b1c19",
        "background": "#fbf9f4",
        "inverse-primary": "#afc8f0",
        "on-tertiary-fixed-variant": "#8c180e",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "on-primary-fixed": "#001c3a",
        "surface-dim": "#dbdad5",
        "on-tertiary-container": "#e45846",
        "on-secondary-fixed": "#241a00",
        "outline-variant": "#c4c6cf"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "section-gap": "80px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "label-md": ["Apple Garamond", "serif"],
        "body-md": ["Apple Garamond", "serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-lg": ["Apple Garamond", "serif"],
        "title-lg": ["Outfit", "sans-serif"],
        "primary": ["Outfit", "sans-serif"],
        "secondary": ["Apple Garamond", "serif"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "title-lg": ["20px", {"lineHeight": "1.5", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
